import Bralette from "../../assets/images/products/bralette.png";
import Jewerrery from "../../assets/images/products/jewerrery.png";
import Cloth from "../../assets/images/products/cloth.png";
import Sandals from "../../assets/images/products/sandals.png";
import Jean from "../../assets/images/products/jean.png";
import Armchair from "../../assets/images/products/armchair.png";

const UserFeed = [
  {
    id: 1,
    profileName: "taznn61",
    name: "Lace bralettes",
    price: "N2,500",
    location: "Lekki, Lagos State",
    img: Bralette,
  },
  {
    id: 2,
    profileName: "but44rr",
    name: "Gold-plated jewellery",
    price: "N12,500",
    location: "Awka, Anambra State",
    img: Jewerrery,
  },
  {
    id: 3,
    profileName: "omach33",
    name: "White printed blouse",
    price: "Donation",
    location: "Oyigbo, Rivers State",
    img: Cloth,
  },
  {
    id: 4,
    profileName: "sleazy66",
    name: "Birkenstock sandals",
    price: "N10,000",
    location: "Benin, Edo State",
    img: Bralette,
  },
  {
    id: 5,
    profileName: "mobani5",
    name: "Jean Shirt",
    price: "Donation",
    location: "Sango, Ogun State",
    img: Jean,
  },
  {
    id: 6,
    profileName: "arita90",
    name: "Single armchair",
    price: "N25,000",
    location: "Elekahia, Rivers State",
    img: Armchair,
  },
  {
    id: 7,
    profileName: "taznn61",
    name: "Lace bralettes",
    price: "N2,500",
    location: "Lekki, Lagos State",
    img: Sandals,
  },
  {
    id: 8,
    profileName: "but44rr",
    name: "Gold-plated jewellery",
    price: "N12,500",
    location: "Awka, Anambra State",
    img: Jewerrery,
  },
  {
    id: 9,
    profileName: "omach33",
    name: "White printed blouse",
    price: "Donation",
    location: "Oyigbo, Rivers State",
    img: Cloth,
  },
  {
    id: 10,
    profileName: "sleazy66",
    name: "Birkenstock sandals",
    price: "N10,000",
    location: "Benin, Edo State",
    img: Sandals,
  },
  {
    id: 11,
    profileName: "mobani5",
    name: "Jean Shirt",
    price: "Donation",
    location: "Sango, Ogun State",
    img: Jean,
  },
  {
    id: 12,
    profileName: "arita90",
    name: "Single armchair",
    price: "N25,000",
    location: "Elekahia, Rivers State",
    img: Armchair,
  },
  {
    id: 13,
    profileName: "taznn61",
    name: "Lace bralettes",
    price: "N2,500",
    location: "Lekki, Lagos State",
    img: Bralette,
  },
  {
    id: 14,
    profileName: "but44rr",
    name: "Gold-plated jewellery",
    price: "N12,500",
    location: "Awka, Anambra State",
    img: Jewerrery,
  },
  {
    id: 15,
    profileName: "omach33",
    name: "White printed blouse",
    price: "Donation",
    location: "Oyigbo, Rivers State",
    img: Cloth,
  },
  {
    id: 16,
    profileName: "sleazy66",
    name: "Birkenstock sandals",
    price: "N10,000",
    location: "Benin, Edo State",
    img: Sandals,
  },
  {
    id: 17,
    profileName: "mobani5",
    name: "Jean Shirt",
    price: "Donation",
    location: "Sango, Ogun State",
    img: Jean,
  },
  {
    id: 18,
    profileName: "arita90",
    name: "Single armchair",
    price: "N25,000",
    location: "Elekahia, Rivers State",
    img: Armchair,
  },
];

export default UserFeed;
